### ISSUE TITLE
Linter is not working correctly

### ISSUE THREAD

**Issue by wellsjo** [wellsjo/JSON-Splora#19]
The editor input type needs to dynamically switch from JavaScript to JSON.

**Comment by vpillinger** [comment]
I tried this and the bigger problem is that turning on the JSON linter will show errors on comments. However, some people might want comments in the data sets which they are using for this type of application. Therefore, we either need to say NO to comments, or find/write a linter that will allow comments.

**Comment by wellsjo** [comment]
@vpillinger you outlined the problem exactly. The spec for this project requires comments, but I couldn't get the linter to not show errors for comments. `json5` is definitely the way to go, since that is already how I'm parsing/validating the editor input.

**Comment by wellsjo** [comment]
fixed by #30
