### ISSUE TITLE
Comments removed on paste

### ISSUE THREAD

**Issue by MaanooAk** [wellsjo/JSON-Splora#24]
On paste the [formatInput()](https://github.com/wellsjo/JSON-Splora/blob/master/app/js/Editor.js#L104) which recreates the Json from the parsed data, so the comments are lost because there are ignored from the parser.

Possible solution: just remove the `formatInput()` on the paste untill a proper format is implemented.

**Comment by wellsjo** [comment]
I think we should keep formatting on-paste, I'm going to label this as a bug instead. The issue is using `JSON.parse` instead of a proper formatter. I tried using `js-beautify` before, but I don't like the way it formats arrays horizontally. Perhaps there is a better beautifier?

**Comment by MaanooAk** [comment]
>  Perhaps there is a better beautifier that handles arrays well?

When inside the array if there is a class then they are formated like the `menu.js`

**Comment by vpillinger** [comment]
This should be easy to make a menu option that allows the user to select between different formatters. Do you think that would be worth it? The majority of the work for doing this has already been completed with adding options to change the Theme.

**Comment by wellsjo** [comment]
@vpillinger I really like that idea...we should also make the formatters configurable

**Comment by vpillinger** [comment]
The problem with hiding the formatter is that there may be other things that differ between the two formatters. I think that in the long run we want to only use `js-beautify` and just provide interface to change the style options. If vertical array formatting is popular enough, then someone can contribute that option to `js-beautify`. If that happens then we can remove the JSON.Stringify option entirely.

**Comment by wellsjo** [comment]
True, I'm down to go with `js-beautify` and make it configurable
