### ISSUE TITLE
integrate with jsoneditor

### ISSUE THREAD

**Issue by qifuren1985** [wellsjo/JSON-Splora#32]
some function in jsoneditor(https://github.com/josdejong/jsoneditor/ , http://jsoneditoronline.org/) is good, maybe we can integrate with jsoneditor.

**Comment by wellsjo** [comment]
What features did you specifically have in mind?

**Comment by qifuren1985** [comment]
the right panel on http://www.jsoneditoronline.org/
It display json structure more intuitively. we can know how many elmenents in a array, how many keys in dict, and we can also find and filter some word quickly.

**Comment by wellsjo** [comment]
this should be re-opened as something specific, then we can decide from there
