### ISSUE TITLE
node-jq throws E2BIG error when input json is too big

### ISSUE THREAD

**Issue by qifuren1985** [wellsjo/JSON-Splora#39]
If input json is big array, it will fail.
for example, type this code in chrome console, it will generate a big array, and copy to clipboard.
`function gen_data() { var ret = []; for(var i=0; i < 10000; i++) { ret.push({"name": i , "kk": i * 2}) } return ret; } copy(JSON.stringify(gen_data()));`

if we type: .length, it will return 10000
if we type: .[0] | keys, it will fail.

two solution:
1.  pass json to node-jq from a temp file
2. modify node-jq, when call child_process to create process, pass json to new process from stdin(faster, and no temp file), not command line. I have add a issue to node-jq.

**Comment by wellsjo** [comment]
For now, we can use the `file` option for `node-jq`, perhaps in conjunction with something like https://github.com/bruce/node-temp
