### ISSUE TITLE
Theme should stay the same

### ISSUE THREAD

**Issue by wellsjo** [wellsjo/JSON-Splora#49]
When you select a theme, close the application, and come back, the theme should be the same

**Comment by MaanooAk** [comment]
This can be generalized to storing settings of all kinds. 
(I understand you like dependencies so) I suggest [conf](https://www.npmjs.com/package/conf) or it's wrapper [electron-config](https://www.npmjs.com/package/electron-config) which stores the files in `app.getPath('userData')`.

**Comment by wellsjo** [comment]
`electron-config` sounds nice. If it properly abstracts the file saving location, I think the dependency is worth it. A settings wrapper class sounds nice here.

**Comment by wellsjo** [comment]
Closed by #55
