### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by wellsjo** [wellsjo/JSON-Splora#51]
unit and functional tests

**Comment by vpillinger** [comment]
I have looked into this a little bit. I think that there are two approaches that make sense. 1) Use something like [Karma](http://karma-runner.github.io/1.0/index.html) for unit testing of custom code. 2) Use a library like [Spectron](https://github.com/electron/spectron) for Component testing of Electron integration.

I am going to start work on implementing Karma tests. I highly recommend that once we get some testing framework in place, that changes without accompanying tests are no longer accepted in the repo.

Something to keep in mind is that there is a lot of work being done in things that are (better as) third-party libraries: parser, linter, ect. Therefore, efforts should be made to add testing to those libraries. We might still want to component test that our use of those libraries are correct (ie, that linter errors are displayed correctly, or that some test inputs are parsed correctly.).

**Comment by wellsjo** [comment]
implemented in #57
