### ISSUE TITLE
Extension for Brackets/Atom/...?

### ISSUE THREAD

**Issue by thany** [wellsjo/JSON-Splora#52]
Would be nicer to have this as an editor extension for Brackets, Atom, etc. Would probably feel nicer than a separate application.

**Comment by davesnx** [comment]
I don't really like auto-promotion, but in this case is what you are searching for...
You can check [atom-jq](https://github.com/sanack/atom-jq) that is the jq inside atom @thany

**Comment by wellsjo** [comment]
Nice! Yes there are definitely other tools available as plugins, but I made this project as a standalone application. It can definitely be modified to work elsewhere though!
