### ISSUE TITLE
Add arguments to command line utility

### ISSUE THREAD

**Issue by wellsjo** [wellsjo/JSON-Splora#54]
Right now we can open from the command line with `jsplora`. We should also allow for arguments. For example:
`jsplora <file>`
`jsplora --input "<json object>"`
`jsplora --input "<json object>" --filter "<filter-string>"`

**Comment by yschimke** [comment]
I suggest a flag also to control between strict jq and javascript modes.

**Comment by wellsjo** [comment]
@yschimke The way the app is currently constructed, `jq` and `javascript` filters are mutually exclusive, as they are abstracted into a single filter function. There isn't a way to choose one or the other.
