### ISSUE TITLE
Issue On install Mac 

### ISSUE THREAD

**Issue by shmdhussain** [wellsjo/JSON-Splora#60]
I am having issue in  installing in MAC OSX 10.10.5 Yosemite, see the Screenshot

![screen shot 2016-12-08 at 13 00 07](https://cloud.githubusercontent.com/assets/4039657/21003620/d391fd66-bd45-11e6-8b4a-cab171207e01.png)

**Comment by wellsjo** [comment]
Hmm...first, you shouldn't have to install with sudo on Mac. What happens without sudo?

**Comment by wellsjo** [comment]
I'm closing this for now.

**Comment by shmdhussain** [comment]
Yes. without sudo installation is working. But when I try to run on any json file I am getting the error as in screenshot
![screen shot 2016-12-12 at 15 24 59](https://cloud.githubusercontent.com/assets/4039657/21097585/9a2c10ca-c07e-11e6-8cab-926c51910032.png)

Am I running it correctly?. Is it possible to test on json data in clipboard(unsaved data)

**Comment by shmdhussain** [comment]
Here is the termoinal screenshot on installing 
![screen shot 2016-12-12 at 15 28 15](https://cloud.githubusercontent.com/assets/4039657/21097641/0cbfa3cc-c07f-11e6-845c-148dc0371d6c.png)

**Comment by wellsjo** [comment]
Ah, it appears you are using an outdated version of node, since it can't understand `destructuring assignment`.  You should update to at least `6.8.1` to get it to work. http://node.green/
