### ISSUE TITLE
jq shorthand filters don't get applied

### ISSUE THREAD

**Issue by yschimke** [wellsjo/JSON-Splora#62]
A jq filter like for getting the text of tweets doesn't work or show any error

`.[].text`

**Comment by wellsjo** [comment]
You are correct. I did a little research and it appears this is a bug with `node-jq`.  I opened a ticket there https://github.com/sanack/node-jq/issues/52

**Comment by luis-conor** [comment]
@wellsjo, the jq issue is closed now, hopefully it's been fixed?

**Comment by wellsjo** [comment]
Wonderful! I'll test

**Comment by wellsjo** [comment]
@luis-conor fixed

**Comment by luis-conor** [comment]
I installed jsplora globally with npm.. @wellsjo, did you updated the npm package?

**Comment by wellsjo** [comment]
@luis-conor I just published `1.0.2` which has the fix

**Comment by luis-conor** [comment]
Works great, awesome.
Thanks!

Can't believe how useful this app is 
🥇 

Is there a way it can be linked into something like /Applications/jsplora.app so I can call it via spotlight/alfred?

**Comment by wellsjo** [comment]
@luis-conor Thanks!

Hmm...I think that would be possible if you cloned the repo and built locally with
```
npm run-script build-darwin
```
That should create `json-splora-darwin-x64/json-splora.app`, which you can drag-and-drop into your Applications folder.

Let me know if that works
