### ISSUE TITLE
Improve installation process

### ISSUE THREAD

**Issue by davesnx** [wellsjo/JSON-Splora#67]
Hello @wellsjo 

I think that isn't the most comfortable way of installing an application the current workflow and we can improve it.

Using something like: [electron-packager](https://github.com/electron-userland/electron-packager)
Allow more users to install the App.

What do you think?

**Comment by wellsjo** [comment]
Hey @davesnx, we are actually using electron-packager to build from npm scripts:
https://github.com/wellsjo/JSON-Splora/blob/master/package.json#L19-L21

How can we improve this?

**Comment by davesnx** [comment]
I mean, that I wanted to install the App with a wizard, not from console. @wellsjo

**Comment by wellsjo** [comment]
Oh yeah, that would be awesome! I'm definitely interested in providing that install process. electron-packager can do that?

**Comment by davesnx** [comment]
Nope @wellsjo 😢

**Comment by wellsjo** [comment]
Ah okay.  Honestly I don't know how to do that lol. I'll update this issue to "improve installation process" and leave it up to whoever knows how 😄

**Comment by davesnx** [comment]
I saw a lot of people using [electron-builder](https://github.com/electron-userland/electron-builder) 

👍

**Comment by wellsjo** [comment]
Ahh, I see, nice. We can definitely go this route.
